// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7e1Xar0KjMuFuBlMlvi7r3_SAuj0vPVs',
    appId: '1:575929234815:web:b19f6d4f02652d4f3a564a',
    messagingSenderId: '575929234815',
    projectId: 'meal-planner-c610f',
    authDomain: 'meal-planner-c610f.firebaseapp.com',
    storageBucket: 'meal-planner-c610f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVRkET4gsAztmC08txq11TbUNjdvL2wFo',
    appId: '1:575929234815:android:ff360d9a906e53d93a564a',
    messagingSenderId: '575929234815',
    projectId: 'meal-planner-c610f',
    storageBucket: 'meal-planner-c610f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT74Wkv07dAfH5M-GVaegonDhvs1HFTvk',
    appId: '1:575929234815:ios:ba5cc01e0ddb8f413a564a',
    messagingSenderId: '575929234815',
    projectId: 'meal-planner-c610f',
    storageBucket: 'meal-planner-c610f.appspot.com',
    iosBundleId: 'com.example.mealPlanner',
  );
}
